### ISSUE TITLE
pi3hat-tool Missing from Pip

### ISSUE THREAD

**Issue by MiNdLiKeAsPoOn** [mjbots/pi3hat#12]
![image](https://user-images.githubusercontent.com/40106812/180179660-009b067b-8eb4-472f-b749-f9d22ad32228.png)

**Comment by jpieper** [comment]
`moteus-pi3hat` can only be installed on a Raspberry Pi running Raspberry Pi OS and some versions of Ubuntu.

`pi3hat_tool` is also not in the pip package, but is available in the separate "tools" package, which is available on the github release page.  It also only runs on the Rasbperry Pi on Linux.

**Comment by MiNdLiKeAsPoOn** [comment]
Understood. Thanks and apologies for the mistake
