### ISSUE TITLE
Hello, may I ask how I can communicate with pi3hat through SPI? Could you please provide an example?

### ISSUE THREAD

**Issue by MaxKingWealth** [mjbots/pi3hat#15]
Hello, may I ask how I can communicate with pi3hat through SPI? Could you please provide an example?

**Comment by jpieper** [comment]
The SPI communication registers are documented, but using them directly with anything other than the pi3hat c++ or python library is not supported.

You can read the SPI registers through the C++ library using pi3hat_tool like so:

```
sudo ./pi3hat_tool --read-spi 2,32,6
```

To read 6 bytes from address 32 on bus 2.

**Comment by MaxKingWealth** [comment]
I don't have raspberry pie on my end, can't I communicate with PI3hat?

**Comment by jpieper** [comment]
You can, but it is not supported.  You will have to read the schematic to understand the RPI pinout and follow the reference manual's instructions for which SPI register contains what data.

**Comment by MaxKingWealth** [comment]
OK，Thanks a lot, I will try to do it
