### ISSUE TITLE
Add support for Python 3.11 to pi3hat_tool

### ISSUE THREAD

**Issue by JGSuw** [mjbots/pi3hat#16]
I would like to add support for Python 3.11 in building pi3hat_tool. Recently, Python 3.11 headers were added to mjbots/bazel_deps, but this added capability is not currently reflected in the build files for pi3hat. This support would be desirable, since currently python3.11 is the only version that is available for Raspian OS and raspberry pi 4. Older versions, such as 3.7, 3.9, and 3.10, must be built from source, which is time consuming.

I have a local branch that has implemented these changes. The changes are modest, and involves small changes to the following files:

- update the commit hash and checksum of the mjbots/bazel_deps github_archive in [pi3hat/tools/workspace/bazel_deps/repository.bzl](https://github.com/mjbots/pi3hat/blob/master/tools/workspace/bazel_deps/repository.bzl) to [806ba633](https://github.com/mjbots/bazel_deps/commit/80b6a3324b6abb5b630f05a8523730c55218860d)
- udpate multiple config_setting in [pi3hat/BUILD](https://github.com/mjbots/pi3hat/blob/master/BUILD)
- add string '3.11' to pyver in [pi3hat/make_release.py](https://github.com/mjbots/pi3hat/blob/c3563cefe31c66d06e2f5e4faa7c2d31ea34eb14/make_release.py#L57)
- add cc_library pybind11_311 to [pi3hat/tools/workspace/pybind11/package.BUILD](https://github.com/mjbots/pi3hat/blob/master/tools/workspace/pybind11/package.BUILD)
- update PYTHON_SHORT_VERSIONS, ABITAG, PTAG, and bdist_wheel filgroup in [pi3hat/lib/python/BUILD](https://github.com/mjbots/pi3hat/blob/master/lib/python/BUILD)
- update cc_binary _pi3hat_router.so in [pi3hat/lib/python/moteus_pi3hat/BUILD](https://github.com/mjbots/pi3hat/blob/master/lib/python/moteus_pi3hat/BUILD) 

I may be missing a few small changes here, but I would like to open a pull request with the permission of @jpieper to review the necessary changes.

**Comment by jpieper** [comment]
No need to ask permission, just open!  I may not take it directly, but will certainly use it for guidance.

**Comment by thestumbler** [comment]
A couple of years ago I was doing a Python project on the Raspberry Pi whose package took a significant amount of time to build. I discovered `piwheels`, infuriatingly spelled with an S unlike its desktop PC counterpart `wheel`. Don't know if that is of any help to you or not.

**Comment by JGSuw** [comment]
@thestumbler not sure if that would help, I'm fairly new to distribution of python packages and OSS in general. I will fork this repo, create new branch with changes, and open a pull request after confirming that all the targets build successfully.

The main thing I need to enable my own use case is that the pi3hat_tools wheel gets built for python 3.11, so that I may install it on my pi4.
